version: '3.8'
services:
  db:
    container_name: score-lib-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: score-lib
      MYSQL_DATABASE: score-lib
      MYSQL_USER: score-lib
      MYSQL_PASSWORD: score-lib
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql

  php:
    container_name: score-lib-php
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - '8080:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug,coverage
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
    volumes:
      - .:/var/www
    depends_on:
      - db
